FROM lambgeo/lambda-gdal:3.2-python3.8

RUN pip install numpy>=1.20.0
RUN pip install pandas
RUN pip install geopandas
RUN pip install rasterio
RUN pip install rio-cogeo
RUN pip install mercantile 
RUN pip install rasterstats
RUN pip install matplotlib
RUN pip install click
RUN pip install shapely
RUN pip install geojson
RUN pip install jupyter
RUN pip install papermill

WORKDIR /mnt
